name: Daily Mutual Fund Update

on:
  schedule:
    # Runs at 09:00 AM UTC (which is 2:30 PM IST)
    # You can change this time later.
    - cron: '0 9 * * *'
  
  # This allows you to click a "Run Now" button manually for testing
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      # 1. Download your code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Install Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 3. Install libraries (Tweepy, Requests)
      - name: Install dependencies
        run: |
          pip install requests tweepy python-dotenv

      # 4. Run the Bot
      - name: Run the script
        env:
          # These grab the secret passwords you will save on GitHub website later
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
        run: python bot.py